### ISSUE TITLE
Synapse Chroma Quick Effects

### ISSUE THREAD

**Issue by nuudlz** [rnd-ash/razer-laptop-control#14]
Hey Ash,
here are some Quick Effect traces for my blade:

Spec:
Model: Razer Blade 15 Adv Early 2019 (Intel i7 8750H; RTX2080)
BIOS: 1.04 (1.05 Update available)
EC: 1.02 (1.03 Update available)
USB: 1.7.0

If you have questions about the traces hit me up in Discord. The filenames should provide basic infos about what I did (p.s. if theres an ABC in the filename that meant I typed a b c)

[RZRSynapseQuickEffectsBlade15Adv19.zip](https://github.com/UKSFM99/razer-laptop-control/files/4010314/RZRSynapseQuickEffectsBlade15Adv19.zip)

If other peeps also would like to provide traces Ill suggest they use this issue instead of opening a new one.

Greetings
nuudlz

**Comment by UKSFM99** [comment]
thank you. Ill use these packets to try and re-implement the Chroma effects. They are all done now in Software rather than openrazer's old way of doing it by setting flags on the keyboard controller.

**Comment by rnd-ash** [comment]
Closing this. We won't be doing hardware effects. All software driven
