### ISSUE TITLE
Deleted Makefile

### ISSUE THREAD

**Issue by MeirBon** [rnd-ash/razer-laptop-control#22]
I saw your post on Reddit and wanted to test out the driver you created. It seems like you deleted your Makefile from the driver folder in one of your last commits.

**Comment by rnd-ash** [comment]
yeah Im currently fighting vscode -.-

**Comment by MeirBon** [comment]
You can always try a different program for your GUI, I like gitkraken myself, or just use the terminal :p

**Comment by rnd-ash** [comment]
Done. Compile now :)

**Comment by MeirBon** [comment]
Thanks! :D

**Comment by waltercool** [comment]
> Thanks! :D

How been you able to compile it? I'm trying but:

`$ make driver
Compiling kernel modules
make -C /lib/modules/5.3.9-waltercool/build M=/home/waltercool/Coding/opensource/razer-laptop-control/driver/src modules
make[1]: Entering directory '/usr/src/linux-5.3'
scripts/Makefile.build:42: /home/waltercool/Coding/opensource/razer-laptop-control/driver/src/Makefile: No such file or directory
make[2]: *** No rule to make target '/home/waltercool/Coding/opensource/razer-laptop-control/driver/src/Makefile'.  Stop.
make[1]: *** [Makefile:1626: _module_/home/waltercool/Coding/opensource/razer-laptop-control/driver/src] Error 2
make[1]: Leaving directory '/usr/src/linux-5.3'
make: *** [Makefile:18: driver] Error 2`

**Comment by waltercool** [comment]
It works now with the last Makefile added, thanks!
