### ISSUE TITLE
Feature Request: RAZER BLADE 15 BASE 2019

### ISSUE THREAD

**Issue by AndLouis** [rnd-ash/razer-laptop-control#27]
Sorry guys,

Id like to ask if anyone has done it work on the razer blade 15 Base model 2019,
In fact I tried to install the dirver and could not use it.

Here are the list of files inside my /sys/module/razercontrol/drivers/hid:Razer laptop System control driver

bind  module  new_id  uevent  unbind

**Comment by rnd-ash** [comment]
hmm, very odd, can you post the output of "dmesg | grep razer"?

**Comment by AndLouis** [comment]
[    4.547679] razerkbd 0003:1532:0246.0002: input,hidraw1: USB HID v1.11 Keyboard [Razer Razer Blade] on usb-0000:00:14.0-8/input0
[    4.820019] razerkbd 0003:1532:0246.0004: input,hidraw3: USB HID v1.11 Mouse [Razer Razer Blade] on usb-0000:00:14.0-8/input2
[    4.907996] razerkbd 0003:1532:0246.0003: input,hidraw2: USB HID v1.11 Keyboard [Razer Razer Blade] on usb-0000:00:14.0-8/input1

**Comment by rnd-ash** [comment]
ah you have openrazer installed, you need to uninstall that first. Try the following:
```
rmmod razerkbd
modprobe razercontrol
```

If those work then that confirms the issue

**Comment by AndLouis** [comment]
had to remove completely the openrazer and now 
"dmesg | grep razer" return an empty

**Comment by AndLouis** [comment]
The PID is 0246

Razer Blade 15 (Mid 2019) Base | 1532:0246

**Comment by rnd-ash** [comment]
ah right. I don't have your device ID in the driver whitelist. Ill add that now

**Comment by rnd-ash** [comment]
Support should be added. GIve it a try

**Comment by AndLouis** [comment]
Hey Ash, thanks it is now working. Great

**Comment by AndLouis** [comment]
just a notice, the make driver_dkms still uses the version 1.0.2 but with the new code from pull :)

**Comment by rnd-ash** [comment]
fixed

**Comment by pozulp** [comment]
@rnd-ash Did you forget to update `driver/src/core.c`? I don't see a `BLADE_2019_BASE` case in the switch statement. Cool driver, btw!

**Comment by rnd-ash** [comment]
oops. yes it appears I did....I keep forgetting to update parts of the driver when I add a new device (too many files to remember to modify)....I'll get round to it later today

**Comment by rnd-ash** [comment]
Fixed now in v1.0.4
