### ISSUE TITLE
Device support: Razer Blade Stealth Late 2019 GTX Model

### ISSUE THREAD

**Issue by jbdrthapa** [rnd-ash/razer-laptop-control#28]
**Device support request for Razer Blade Stealth Late 2019 GTX Model**

Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 004: ID **1532:024a** Razer USA, Ltd Razer Blade
Bus 003 Device 003: ID 13d3:56d5 IMC Networks Integrated Camera
Bus 003 Device 005: ID 8087:0026 Intel Corp. 
Bus 003 Device 002: ID 1532:007b Razer USA, Ltd Razer Viper Ultimate Dongle
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by rnd-ash** [comment]
Done. Try Version 1.0.4

**Comment by jbdrthapa** [comment]
Thanks for adding support for this device. I tried using the AUR package the package gets added, built, and installed by doesn't get loaded upon reboot.

I looked at your commit and may have found an issue. 

in razer_common.c adding BLADE_2019_STEALTH_GTX to hid_device_id table[] ?

**Comment by rnd-ash** [comment]
damn it I'm always forgetting to do something :/. I'll so that later today

**Comment by rnd-ash** [comment]
fixed

**Comment by jbdrthapa** [comment]
thanks that fixed the issue, just installed it.
