### ISSUE TITLE
make fails on rgb_test_service

### ISSUE THREAD

**Issue by Skrappjaw** [rnd-ash/razer-laptop-control#31]
```
 make
Scanning dependencies of target rgb_test
[ 20%] Building CXX object CMakeFiles/rgb_test.dir/src/main.cpp.o
/home/skrapp/razer-laptop-control/rgb_test_service/src/main.cpp:3:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/rgb_test.dir/build.make:62: recipe for target 'CMakeFiles/rgb_test.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/rgb_test.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/rgb_test.dir/all' failed
make[1]: *** [CMakeFiles/rgb_test.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by rnd-ash** [comment]
Hmmm looks like you are running an older version of c++. see if you can replace the line in the file it's complaining about to say

#include <experimental/filesystem>

**Comment by Skrappjaw** [comment]
I did as suggested with that line and others that threw the same error. And now this. Is there a full list of dependencies?


` make
[ 20%] Building CXX object CMakeFiles/rgb_test.dir/src/main.cpp.o
In file included from /home/skrapp/razer-laptop-control/rgb_test_service/src/main.cpp:7:0:
/home/skrapp/razer-laptop-control/rgb_test_service/src/effects.h:5:10: fatal error: X11/Xlib.h: No such file or directory
 #include "X11/Xlib.h"
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/rgb_test.dir/build.make:62: recipe for target 'CMakeFiles/rgb_test.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/rgb_test.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/rgb_test.dir/all' failed
make[1]: *** [CMakeFiles/rgb_test.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by rnd-ash** [comment]
you don't have x11 libs installed.

try installing libx11-dev, or some other similar named package that installs those libraries

**Comment by Skrappjaw** [comment]
i started from /scratch and tried from a fresh git clone.... is there a full list of dependencies for  compiling this?

> make
> Scanning dependencies of target rgb_test
> [ 20%] Building CXX object CMakeFiles/rgb_test.dir/src/main.cpp.o
> /home/skrapp/razer-laptop-control/rgb_test_service/src/main.cpp:3:10: fatal error: filesystem: No such file or directory
>  #include <filesystem>
>           ^~~~~~~~~~~~
> compilation terminated.
> CMakeFiles/rgb_test.dir/build.make:62: recipe for target 'CMakeFiles/rgb_test.dir/src/main.cpp.o' failed
> make[2]: *** [CMakeFiles/rgb_test.dir/src/main.cpp.o] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/rgb_test.dir/all' failed
> make[1]: *** [CMakeFiles/rgb_test.dir/all] Error 2
> Makefile:116: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by Skrappjaw** [comment]
after some research.... I found i need to be using gcc-8 or better to compile this without the experimental/filesystem line... BUT, in attempting to install it, I'm now looking at this...

```
make
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

    /usr/bin/c++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

```

**Comment by Skrappjaw** [comment]
solved.... gcc version 9 required. here's the link to the install instructions for those on 18.04

https://linuxize.com/post/how-to-install-gcc-compiler-on-ubuntu-18-04/
