### ISSUE TITLE
[BUG] usr/bin/ld: cannot find -lnotify

### ISSUE THREAD

**Issue by zaanposni** [rnd-ash/razer-laptop-control#32]
**Describe the bug**
When running `make` in `/rgb_test_service/` some compiling stuff fails 
```
usr/bin/ld: cannot find -lnotify
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/rgb_test.dir/build.make:129: rgb_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:860: CMakeFiles/rgb_test.dir/all] Error 2
make: *** [Makefile:117: all] Error 2
```

**To Reproduce**

- pull newest state
- install drivers
- follow instructions of rgb_test

**Expected behavior**
install everything correctly and handle dependencies

**Optional stuff**

I am on a new installed ubuntu 20 LTS without special configuration.
I had to install libnotify-dev.
**NOTE: it has to be libnotify-dev and not libnotify**
```
sudo apt-get install libnotify-dev
```
After installing libnotify-dev everything works fine as expected.

I am not very familiar with your compiling stuff so please understand that I cannot open a pull request to handle the missing dependency correctly.

**Comment by rnd-ash** [comment]
you need to install the libnotify libraries.

**Comment by zaanposni** [comment]
sure thing, thats what I wrote. Just wanted to tell you that the dependency is not handled correctly.

**Comment by Skrappjaw** [comment]
I figured this out also. Maybe add to the read me instructions. along with gcc-9 g++-9 requirements.
