### ISSUE TITLE
[BUG] Razercontrol module is not loaded!

### ISSUE THREAD

**Issue by gustav111** [rnd-ash/razer-laptop-control#33]
**Describe the bug**
When trying to use the rgb_test CLI this error message shows up:
```
Razercontrol module is not loaded!
```

**To Reproduce**

Ubuntu 20.04 LTS
Install drivers as stated
Install rgb_test as stated
Try to run a rgb_test command as in your examples.

**Expected behavior**
CLI should work or give more helpful output.

**Optional info**
I am not familiar with driver stuff but I guess I made a mistake while installing those and updating . I used:
```
sudo update-initramfs -u && sudo update-grub
sudo reboot
```

**Comment by rnd-ash** [comment]
hmmm. do "lsmod | grep razer"

if the razer control driver is not there then it means the driver isn't loaded. 

how did you compile and install the driver?

**Comment by gustav111** [comment]
```
$ lsmod | grep razer
razerkbd               73728  0
hid                   131072  5 i2c_hid,usbhid,hid_multitouch,razerkbd,hid_generic
```

I did:
```
cd driver
sudo rmmod razerkbd
sudo make driver_dkms
sudo dkms add -m razercontrol -v 1.0.4
sudo dkms build -m razercontrol -v 1.0.4
sudo update-initramfs -u && sudo update-grub
sudo reboot

cd rgb_test_service
cmake .
make
```

**Comment by rnd-ash** [comment]
right I see the problem.

uninstall razerkbd driver (part of openrazer).

that driver blocks my driver from loading unfortunately

**Comment by gustav111** [comment]
I used:
```
dpkg -l | grep -i nvidia
```
to list all drivers installed. There were like 3 items installed.

Then I did:
```
sudo apt-get remove --purge '.*razer.*'
```
Then running the first command again returns no results obviously.

**But** when I follow the installation again as described above I get the same error "razercontrol module is not loaded" although `lsmod | grep razer` returns no results anymore.

**Comment by mariusstaicu** [comment]
same for me on ubuntu 19.10

**Comment by MattHarr1s** [comment]
I'm having the same issue in Pop_OS 20.04.

**Comment by Azuliana** [comment]
This was also happening on Manjaro 20.0.3

**Comment by rnd-ash** [comment]
do any of you guys have openrazer installed? run lsmod and see if openrazer is listed....you need to unfortunately uninstall that before the laptop driver can load

**Comment by rnd-ash** [comment]
I can however confirm that the driver loads on my Ubuntu VM and arch host...

**Comment by MattHarr1s** [comment]
I don't have openrazer installed. I eventually got the module to load by running  `sudo dkms install razercontrol/1.0.4`  after the build step.
