### ISSUE TITLE
[BUG] Add Razer Blade 2020 Advanced Support

### ISSUE THREAD

**Issue by tbiehn** [rnd-ash/razer-laptop-control#35]
Bus 001 Device 003: ID 1532:0253 Razer USA, Ltd Razer Blade

razer-hardware/razer-laptop-control/driver/src/core.c:
   21  	case BLADE_2019_ADV:
   22  		return "Blade 15 2019 Advanced";
   23: 	case BLADE_2020_ADV:
   24  		return "Blade 15 2020 Advanced";
   25  	case BLADE_2019_MERC:

razer-hardware/razer-laptop-control/driver/src/defines.h:
   14  #define BLADE_2019_ADV 0x023A
   15  #define BLADE_2019_MERC 0x0245
   16: #define BLADE_2020_ADV 0x0253

razer-hardware/razer-laptop-control/driver/src/fancontrol.c:
   18  		return MAX_FAN_RPM_2018_BLADE;
   19  	case BLADE_2019_ADV:
   20: 	case BLADE_2020_ADV:
   21  	case BLADE_2019_MERC:
   22  	case BLADE_PRO_2019:
   ..
   44  	switch (product_id) {
   45  	case BLADE_2019_ADV:
   46: 	case BLADE_2020_ADV:
   47  	case BLADE_2019_MERC:
   48  		return 1;

razer-hardware/razer-laptop-control/driver/src/razer_common.c:
  383  	{ HID_USB_DEVICE(RAZER_VENDOR_ID, BLADE_2019_BASE)},
  384  	{ HID_USB_DEVICE(RAZER_VENDOR_ID, BLADE_2019_ADV)},
  385: 	{ HID_USB_DEVICE(RAZER_VENDOR_ID, BLADE_2020_ADV)},

**Comment by rnd-ash** [comment]
alright I shall add this tomorrow.

**Comment by rnd-ash** [comment]
Completed. Should be in v1.1.0
