### ISSUE TITLE
[BUG] RazerDaemon errors on start from boot

### ISSUE THREAD

**Issue by nalin29** [rnd-ash/razer-laptop-control#41]
The daemon errors out when booting, after logging in then restarting the daemon using the exec as root allows the daemon to work. 

`razerdaemon.service - Razer laptop control daemon
     Loaded: loaded (/etc/systemd/system/razerdaemon.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Mon 2020-07-27 21:08:59 CDT; 47s ago
    Process: 889 ExecStart=/usr/share/razercontrol/daemon (code=exited, status=101)
   Main PID: 889 (code=exited, status=101)

Jul 27 21:08:59 nalin-blade-manjaro systemd[1]: Started Razer laptop control daemon.
Jul 27 21:08:59 nalin-blade-manjaro daemon[889]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/driver_sysfs.rs:11:15
Jul 27 21:08:59 nalin-blade-manjaro daemon[889]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jul 27 21:08:59 nalin-blade-manjaro systemd[1]: razerdaemon.service: Main process exited, code=exited, status=101/n/a
Jul 27 21:08:59 nalin-blade-manjaro systemd[1]: razerdaemon.service: Failed with result 'exit-code'.`

**Comment by rnd-ash** [comment]
Fixed in 849cf607eabeac571e1c8b92282c681701ff693c
