### ISSUE TITLE
[FEATURE] Access to new boost option

### ISSUE THREAD

**Issue by phush0** [rnd-ash/razer-laptop-control#46]
For advanced model 2020 there is new option for CPU power named BOOST, which increase TDP value to 85W short and 55W for long term. Can we have access to it pls?

**Comment by phush0** [comment]
If I know how to capture packets I can implement in other tree and make pull request

**Comment by rnd-ash** [comment]
right so basically you'll need to install USBPCAP in windows, unplug everything USB related from your device, turn OFF RGB effects in synapse, then begin doing a series of captures.

for each capture, go to synapse and change a setting (say enable or disable boost mode) about 5 times. then stop capturing and label th packet capture file as to what you did

do this many times for each new feature (for example the CPU boost seems to be a slider), so have one capture with moving it from the lowest setting to the next setting and back again and again

then throw all those into a zip and upload them here so I can take a look as well

**Comment by phush0** [comment]
One interesting fact I have found is that if I use virtual machine to record packets and than turn it off, light effect programmed in Razer Synapse will stick, and keyboard will continue to animate by itself even after reboot, but power option is back to default - balanced. If I force remove USB device from virtual machine - effect will not play and will stick to color it is currently set, but power option will remain until I reboot.

**Comment by phush0** [comment]
here capture of the two custom sliders in Synapse
CPU - low->medium->high->boost
GPU - low->medium->high
[synapse3-custom-sliders.zip](https://github.com/rnd-ash/razer-laptop-control/files/5154794/synapse3-custom-sliders.zip)

**Comment by phush0** [comment]
Actually this is incomplete, custom mode is 0x04.
```
            buffer[5] = 0x03;
            buffer[6] = 0x0d;
            buffer[7] = 0x87;
            buffer[8] = 0x00;
            buffer[9] = 0x02;
            buffer[10] = 0x00;
            buffer[11] = 0x00;
            send_payload(laptop->usb_dev, buffer, 3400, 3800);

            buffer[5] = 0x03;
            buffer[6] = 0x0d;
            buffer[7] = 0x07;
            buffer[8] = 0x00;
            buffer[9] = 0x02;
            buffer[10] = 0x02;
            buffer[11] = 0x00;
            send_payload(laptop->usb_dev, buffer, 3400, 3800);
```
I don't know why you have to call it with byte 7 set once on 0x87 and one time 0x07 - maybe 0x80 is clear/set bit ? This is for GPU boost. So basically I have make it work. Now it have to be added custom mode - 4 and set cpu boost/gpu boost. Both in driver and in daemon/cli.
